

export default function handler(req, res) {   

      const complianceRecords = [
      // ---------------- 0100578962 ----------------
      {
        id: "ce1",
        loan_number: "0100578962",
        req_num: 1,
        date: "04/12/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "jack milton",
        trans_date: "06/12/2025",
        trans_time: "20:45:29.199",
        trid_monitor: "Pass"
      },
      {
        id: "ce2",
        loan_number: "0100578962",
        req_num: 2,
        date: "04/12/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "emma stone",
        trans_date: "06/12/2025",
        trans_time: "21:10:11.100",
        trid_monitor: "Pass"
      },
      {
        id: "ce3",
        loan_number: "0100578962",
        req_num: 3,
        date: "04/12/2025",
        userid: "web",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data check",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "liam carter",
        trans_date: "06/12/2025",
        trans_time: "22:05:33.210",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578972 ----------------
      {
        id: "ce4",
        loan_number: "0100578972",
        req_num: 1,
        date: "04/13/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "fail",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "olivia smith",
        trans_date: "06/13/2025",
        trans_time: "10:12:01.999",
        trid_monitor: "Pass"
      },
      {
        id: "ce5",
        loan_number: "0100578972",
        req_num: 2,
        date: "04/13/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "fail",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "noah johnson",
        trans_date: "06/13/2025",
        trans_time: "11:45:22.321",
        trid_monitor: "Pass"
      },
      {
        id: "ce6",
        loan_number: "0100578972",
        req_num: 3,
        date: "04/13/2025",
        userid: "api",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "fail",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "missing doc",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "ava brown",
        trans_date: "06/13/2025",
        trans_time: "12:30:45.450",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578982 ----------------
      {
        id: "ce7",
        loan_number: "0100578982",
        req_num: 1,
        date: "04/14/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "william davis",
        trans_date: "06/14/2025",
        trans_time: "09:10:10.101",
        trid_monitor: "Pass"
      },
      {
        id: "ce8",
        loan_number: "0100578982",
        req_num: 2,
        date: "04/14/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "sophia miller",
        trans_date: "06/14/2025",
        trans_time: "09:55:55.555",
        trid_monitor: "Pass"
      },
      {
        id: "ce9",
        loan_number: "0100578982",
        req_num: 3,
        date: "04/14/2025",
        userid: "web",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data mismatch",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "james wilson",
        trans_date: "06/14/2025",
        trans_time: "10:40:40.404",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578991 ----------------
      {
        id: "ce10",
        loan_number: "0100578991",
        req_num: 1,
        date: "04/15/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "fail",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "jack milton",
        trans_date: "06/15/2025",
        trans_time: "08:11:11.111",
        trid_monitor: "Pass"
      },
      {
        id: "ce11",
        loan_number: "0100578991",
        req_num: 2,
        date: "04/15/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "fail",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "emma stone",
        trans_date: "06/15/2025",
        trans_time: "09:22:22.222",
        trid_monitor: "Pass"
      },
      {
        id: "ce12",
        loan_number: "0100578991",
        req_num: 3,
        date: "04/15/2025",
        userid: "api",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "fail",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "review needed",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "liam carter",
        trans_date: "06/15/2025",
        trans_time: "10:33:33.333",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578992 ----------------
      {
        id: "ce13",
        loan_number: "0100578992",
        req_num: 1,
        date: "04/16/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "fail",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "olivia smith",
        trans_date: "06/16/2025",
        trans_time: "11:11:11.111",
        trid_monitor: "Pass"
      },
      {
        id: "ce14",
        loan_number: "0100578992",
        req_num: 2,
        date: "04/16/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "fail",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "noah johnson",
        trans_date: "06/16/2025",
        trans_time: "12:22:22.222",
        trid_monitor: "Pass"
      },
      {
        id: "ce15",
        loan_number: "0100578992",
        req_num: 3,
        date: "04/16/2025",
        userid: "web",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "fail",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data breach",
        trans_method: "order",
        trans_status: "rejected",
        trans_user: "ava brown",
        trans_date: "06/16/2025",
        trans_time: "13:33:33.333",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578911 ----------------
      {
        id: "ce16",
        loan_number: "0100578911",
        req_num: 1,
        date: "04/17/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "william davis",
        trans_date: "06/17/2025",
        trans_time: "08:01:01.101",
        trid_monitor: "Pass"
      },
      {
        id: "ce17",
        loan_number: "0100578911",
        req_num: 2,
        date: "04/17/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "sophia miller",
        trans_date: "06/17/2025",
        trans_time: "09:02:02.202",
        trid_monitor: "Pass"
      },
      {
        id: "ce18",
        loan_number: "0100578911",
        req_num: 3,
        date: "04/17/2025",
        userid: "api",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data check",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "james wilson",
        trans_date: "06/17/2025",
        trans_time: "10:03:03.303",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578912 ----------------
      {
        id: "ce19",
        loan_number: "0100578912",
        req_num: 1,
        date: "04/18/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "isabella moore",
        trans_date: "06/18/2025",
        trans_time: "11:11:11.111",
        trid_monitor: "Pass"
      },
      {
        id: "ce20",
        loan_number: "0100578912",
        req_num: 2,
        date: "04/18/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "jack milton",
        trans_date: "06/18/2025",
        trans_time: "12:12:12.121",
        trid_monitor: "Pass"
      },
      {
        id: "ce21",
        loan_number: "0100578912",
        req_num: 3,
        date: "04/18/2025",
        userid: "web",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data mismatch",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "emma stone",
        trans_date: "06/18/2025",
        trans_time: "13:13:13.131",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578913 ----------------
      {
        id: "ce22",
        loan_number: "0100578913",
        req_num: 1,
        date: "04/19/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "fail",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "liam carter",
        trans_date: "06/19/2025",
        trans_time: "09:09:09.090",
        trid_monitor: "Pass"
      },
      {
        id: "ce23",
        loan_number: "0100578913",
        req_num: 2,
        date: "04/19/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "fail",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "olivia smith",
        trans_date: "06/19/2025",
        trans_time: "10:10:10.100",
        trid_monitor: "Pass"
      },
      {
        id: "ce24",
        loan_number: "0100578913",
        req_num: 3,
        date: "04/19/2025",
        userid: "api",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "fail",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "missing info",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "noah johnson",
        trans_date: "06/19/2025",
        trans_time: "11:11:11.110",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578914 ----------------
      {
        id: "ce25",
        loan_number: "0100578914",
        req_num: 1,
        date: "04/20/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "ava brown",
        trans_date: "06/20/2025",
        trans_time: "08:08:08.080",
        trid_monitor: "Pass"
      },
      {
        id: "ce26",
        loan_number: "0100578914",
        req_num: 2,
        date: "04/20/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "william davis",
        trans_date: "06/20/2025",
        trans_time: "09:09:09.090",
        trid_monitor: "Pass"
      },
      {
        id: "ce27",
        loan_number: "0100578914",
        req_num: 3,
        date: "04/20/2025",
        userid: "web",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data mismatch",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "sophia miller",
        trans_date: "06/20/2025",
        trans_time: "10:10:10.100",
        trid_monitor: "Fail"
      },
    
      // ---------------- 0100578919 ----------------
      {
        id: "ce28",
        loan_number: "0100578919",
        req_num: 1,
        date: "04/21/2025",
        userid: "api",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "success",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no issue",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "james wilson",
        trans_date: "06/21/2025",
        trans_time: "11:11:11.111",
        trid_monitor: "Pass"
      },
      {
        id: "ce29",
        loan_number: "0100578919",
        req_num: 2,
        date: "04/21/2025",
        userid: "web",
        req_score: "pass",
        trid: "N/A",
        req_type: "HCL",
        status: "error",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "no reason",
        trans_method: "order",
        trans_status: "complete",
        trans_user: "isabella moore",
        trans_date: "06/21/2025",
        trans_time: "12:12:12.121",
        trid_monitor: "Pass"
      },
      {
        id: "ce30",
        loan_number: "0100578919",
        req_num: 3,
        date: "04/21/2025",
        userid: "api",
        req_score: "fail",
        trid: "N/A",
        req_type: "HCL",
        status: "warning",
        method: "order",
        is_hoepa: "pass",
        is_hpml: "pass",
        st_local_pred: "pass",
        tila_trid: "pass",
        respa: "pass",
        qm: "pass",
        st_agency_gline: "pass",
        licence_audit: "pass",
        ov_reason: "data check",
        trans_method: "order",
        trans_status: "pending",
        trans_user: "jack milton",
        trans_date: "06/21/2025",
        trans_time: "13:13:13.131",
        trid_monitor: "Fail"
      }
    ];  
    const { loanNumber } = req.query;  
    // Get all complianceRecords for this loan
    const records = complianceRecords.filter(r => r.loan_number === loanNumber);  
    if (records.length > 0) {
      res.status(200).json(records);
    } else {
      res.status(404).json({ message: "No records found for this loan number" });
    }  
}
