export default function handler(req, res) {   

          const loans = [
            {
              id: "L1",
              loan_number: "0100578962",
              loanType: "FHA",
              loan_amount: 199999,
              loan_status: "Approved",
              borrower_name: "John Anderson Jack Rose",
              interest_rate: 9.45,
              property_address: "29 Lakeview Dr, Austin, TX, USA",
              property_type: "Single Family",
              occupancy: "Owner-Occupied",
              support_center: "SC2",
              cema: "Yes",
              division: "West",
              cashout: "Yes",
              doc_type: "Full Doc",
              closing_agent: "Lone Star Title",
              product: "30Y Fixed",
              loan_purpose: "Purchase",
              funding_rework_ti: "No",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-01-01",
              schl_disb_date: "2026-02-02",
              first_payment_date: "2026-03-03"
            },
            {
              id: "L2",
              loan_number: "0100578972",
              loanType: "VA Loan",
              loan_amount: 640000,
              loan_status: "Approved",
              borrower_name: "Emily Roberts",
              interest_rate: 6.35,
              property_address: "88 Ocean Ave, Miami, FL, USA",
              property_type: "Condo",
              occupancy: "Owner-Occupied",
              support_center: "SC1",
              cema: "Yes",
              division: "South",
              cashout: "Yes",
              doc_type: "Full Doc",
              closing_agent: "Sun Coast Closings",
              product: "30Y Fixed",
              loan_purpose: "Refinance",
              funding_rework_ti: "No",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-02-05",
              schl_disb_date: "2026-02-10",
              first_payment_date: "2026-04-01"
            },
            {
              id: "L3",
              loan_number: "0100578982",
              loanType: "FHA/VA Loan",
              loan_amount: 710000,
              loan_status: "Pending",
              borrower_name: "Michael Thompson",
              interest_rate: 6.6,
              property_address: "245 Hill St, Denver, CO, USA",
              property_type: "Single Family",
              occupancy: "Owner-Occupied",
              support_center: "SC2",
              cema: "No",
              division: "West",
              cashout: "No",
              doc_type: "Full Doc",
              closing_agent: "Mountain Peak Title",
              product: "30Y Fixed",
              loan_purpose: "Purchase",
              funding_rework_ti: "Yes",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-03-01",
              schl_disb_date: "2026-03-06",
              first_payment_date: "2026-05-01"
            },
            {
              id: "L4",
              loan_number: "0100578991",
              loanType: "Jumbo Loan",
              loan_amount: 480000,
              loan_status: "Approved",
              borrower_name: "Sarah White",
              interest_rate: 6.25,
              property_address: "390 Sunset Blvd, Los Angeles, CA, USA",
              property_type: "Townhouse",
              occupancy: "Owner-Occupied",
              support_center: "SC1",
              cema: "Yes",
              division: "West",
              cashout: "Yes",
              doc_type: "Full Doc",
              closing_agent: "Pacific Horizon Title",
              product: "15Y Fixed",
              loan_purpose: "Refinance",
              funding_rework_ti: "No",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-01-20",
              schl_disb_date: "2026-01-25",
              first_payment_date: "2026-03-01"
            },
            {
              id: "L5",
              loan_number: "0100578992",
              loanType: "Govt 10 year",
              loan_amount: 390000,
              loan_status: "Rejected",
              borrower_name: "David Harris",
              interest_rate: 6.95,
              property_address: "75 Lincoln Ave, Chicago, IL, USA",
              property_type: "Apartment",
              occupancy: "Rented",
              support_center: "SC2",
              cema: "No",
              division: "Midwest",
              cashout: "Yes",
              doc_type: "Low Doc",
              closing_agent: "Great Lakes Closings",
              product: "30Y Fixed",
              loan_purpose: "Purchase",
              funding_rework_ti: "Yes",
              payofff_shortage_ti: "Yes",
              schl_closing_date: "2026-02-18",
              schl_disb_date: "2026-02-22",
              first_payment_date: "2026-04-10"
            },
            {
              id: "L6",
              loan_number: "0100578911",
              loanType: "Govt 20 year",
              loan_amount: 830000,
              loan_status: "Approved",
              borrower_name: "Jessica Clark",
              interest_rate: 6.2,
              property_address: "510 Broadway, New York, NY, USA",
              property_type: "Condo",
              occupancy: "Owner-Occupied",
              support_center: "SC1",
              cema: "Yes",
              division: "Northeast",
              cashout: "No",
              doc_type: "Full Doc",
              closing_agent: "Empire State Title",
              product: "30Y Fixed",
              loan_purpose: "Purchase",
              funding_rework_ti: "No",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-01-14",
              schl_disb_date: "2026-01-19",
              first_payment_date: "2026-03-01"
            },
            {
              id: "L7",
              loan_number: "0100578912",
              loanType: "Govt 25 year",
              loan_amount: 560000,
              loan_status: "Pending",
              borrower_name: "Christopher Lewis",
              interest_rate: 6.7,
              property_address: "1400 Beacon St, Boston, MA, USA",
              property_type: "Condo",
              occupancy: "Owner-Occupied",
              support_center: "SC3",
              cema: "No",
              division: "Northeast",
              cashout: "No",
              doc_type: "Full Doc",
              closing_agent: "Liberty Title Group",
              product: "ARM 5/1",
              loan_purpose: "Purchase",
              funding_rework_ti: "Yes",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-03-05",
              schl_disb_date: "2026-03-10",
              first_payment_date: "2026-05-01"
            },
            {
              id: "L8",
              loan_number: "0100578913",
              loanType: "Govt 25 year",
              loan_amount: 600000,
              loan_status: "Approved",
              borrower_name: "Amanda Walker",
              interest_rate: 6.5,
              property_address: "210 Desert Rd, Phoenix, AZ, USA",
              property_type: "Single Family",
              occupancy: "Owner-Occupied",
              support_center: "SC1",
              cema: "Yes",
              division: "West",
              cashout: "Yes",
              doc_type: "Full Doc",
              closing_agent: "Desert Valley Title",
              product: "30Y Fixed",
              loan_purpose: "Cash-Out Refinance",
              funding_rework_ti: "No",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-02-08",
              schl_disb_date: "2026-02-13",
              first_payment_date: "2026-04-01"
            },
            {
              id: "L9",
              loan_number: "0100578914",
              loanType: "Govt 10 year",
              loan_amount: 455000,
              loan_status: "Approved",
              borrower_name: "Daniel Hall",
              interest_rate: 6.8,
              property_address: "33 Peachtree St, Atlanta, GA, USA",
              property_type: "Townhouse",
              occupancy: "Owner-Occupied",
              support_center: "SC2",
              cema: "No",
              division: "South",
              cashout: "Yes",
              doc_type: "Full Doc",
              closing_agent: "Peach Title Services",
              product: "30Y Fixed",
              loan_purpose: "Purchase",
              funding_rework_ti: "Yes",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-03-12",
              schl_disb_date: "2026-03-18",
              first_payment_date: "2026-05-10"
            },
            {
              id: "L10",
              loan_number: "0100578919",
              loanType: "Govt 25 year",
              loan_amount: 920000,
              loan_status: "Approved",
              borrower_name: "Olivia Young",
              interest_rate: 6.15,
              property_address: "77 Market St, San Francisco, CA, USA",
              property_type: "Single Family",
              occupancy: "Owner-Occupied",
              support_center: "SC1",
              cema: "Yes",
              division: "West",
              cashout: "No",
              doc_type: "Full Doc",
              closing_agent: "Golden Gate Title",
              product: "15Y Fixed",
              loan_purpose: "Refinance",
              funding_rework_ti: "No",
              payofff_shortage_ti: "No",
              schl_closing_date: "2026-01-25",
              schl_disb_date: "2026-01-30",
              first_payment_date: "2026-03-01"
            }
          ];

           const { loanNumber } = req.query;
        //const loanNumber = req.params.loanNumber;
        
        const loan = loans.find(l => l.loan_number === loanNumber);
        
        if (loan) {
          res.status(200).json(loan);
        } else {
          res.status(404).json({ message: "Loan not found" });
        }
  
}
